# Generated by Django 5.1.3 on 2024-11-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('rating', models.CharField(max_length=5)),
                ('overview', models.CharField(max_length=500)),
                ('poster', models.URLField()),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.category')),
            ],
        ),
    ]
