# Generated by Django 5.0.6 on 2025-02-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='movie',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(),
        ),
    ]
