# Generated by Django 5.0.6 on 2025-02-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_vote_count_movie_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='vector',
            field=models.BinaryField(null=True),
        ),
    ]
