# Generated by Django 5.0.6 on 2025-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_year_alter_movie_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
